name: Build RPMs and push to GHCR

on:
  workflow_dispatch:

env:
  OCI_REPO: ghcr.io/${{ github.repository }}

jobs:
  versions:
    runs-on: ubuntu-latest

    outputs:
      versions: ${{ steps.read-versions.outputs.versions }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Read versions.yaml
        id: read-versions
        shell: bash
        run: |
          versions=$(yq -o=json -I=0 '.' versions.yaml)
          echo "versions=$versions" >> $GITHUB_OUTPUT

  build:
    needs: versions
    strategy:
      matrix:
        fedora-version: ${{ fromJSON(needs.versions.outputs.versions).fedora-versions }}

    runs-on: ubuntu-latest
    container:
      image: fedora:${{ matrix.fedora-version }}
      options: --privileged

    env:
      FEDORA_VERSION: ${{ matrix.fedora-version }}
      PROJECT_VERSION: ${{ fromJSON(needs.versions.outputs.versions).project-version }}

    steps:
      - name: Setup ORAS
        uses: oras-project/setup-oras@v2.0.1

      - name: Check for existing build
        id: check-existing
        shell: bash
        run: |
          OCI_TAG="f$FEDORA_VERSION-$PROJECT_VERSION"
          echo "OCI_TAG=$OCI_TAG" >> $GITHUB_ENV

          echo "REPO: $OCI_REPO:$OCI_TAG"
          if oras manifest fetch "$OCI_REPO:$OCI_TAG" > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "::notice::Skipping build, artifact with content hash $OCI_TAG already exists"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "No existing artifact for $OCI_TAG, proceeding with build"
          fi

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup build environment
        shell: bash
        run: |
          dnf install -y rpmdevtools
          mkdir -p ./rpms

      - name: Download source code
        shell: bash
        run: |
          curl -fsSL "https://github.com/johnfanv2/LenovoLegionLinux/archive/refs/tags/$PROJECT_VERSION.tar.gz" -o ./source.tar.gz
          mkdir -p ./source
          tar -xzf ./source.tar.gz -C ./source --strip-components=1
          rm -f ./source.tar.gz

      - name: Build "dkms-LenovoLegionLinux" RPM
        uses: ./.github/actions/build-rpm
        with:
          specfile: ./source/deploy/build_packages/lenovolegionlinux-dkms.spec
          outdir: ./rpms

      - name: Build "python-darkdetect" RPM
        uses: ./.github/actions/build-rpm
        with:
          specfile: ./source/deploy/build_packages/darkdetect.spec
          outdir: ./rpms

      - name: Build "python-LenovoLegionLinux" RPM
        uses: ./.github/actions/build-rpm
        with:
          specfile: ./source/deploy/build_packages/lenovolegionlinux.spec
          outdir: ./rpms

      - run: ls -l ./rpms
