name: Update Fedora and project versions

on:
  schedule:
    - cron: "05 10 * * *" # 10:05am UTC everyday
  workflow_dispatch:

jobs:
  update-versions:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Read versions.yaml
        id: read-versions
        shell: bash
        run: |
          versions=$(yq -o=json -I=0 '.' versions.yaml)
          echo "versions=$versions" >> $GITHUB_OUTPUT

      - name: Get latest Fedora versions
        id: latest-fedora-versions
        shell: bash
        run: |
          latest_versions=$(curl -fsSL -H "Accept: application/json" "https://bodhi.fedoraproject.org/releases/?state=current" | \
            jq -r '[.releases[] | select(.id_prefix=="FEDORA" and (.name | test("Flatpaks") | not)) | .version | tonumber] | sort_by(-.) | tostring')
          echo "latest_versions_json=$latest_versions" >> $GITHUB_OUTPUT

      - name: Get latest LenovoLegionLinux version
        id: latest-project-version
        shell: bash
        run: |
          latest_version=$(curl -fsSL "https://api.github.com/repos/johnfanv2/LenovoLegionLinux/tags" | jq '.[0].name')
          echo "latest_version=$latest_version" >> $GITHUB_OUTPUT

      - name: Update versions.yaml
        shell: bash
        run: |
          fedora_versions_json="${{ steps.latest-fedora-versions.outputs.latest_versions_json }}"
          project_version="${{ steps.latest-project-version.outputs.latest_version }}"
          json_value=$(jq -rn --argjson fedora-versions "$fedora_versions_json" --arg project-version "$project_version" '$ARGS.named | tostring')
          yaml_value=$(echo "$json_value" | yq -P)
          echo "$yaml_value" > versions.yaml

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Update Fedora and project versions"
          file_pattern: "versions.yaml"
